#!/usr/bin/env node
var reporter = require('nodeunit').reporters.default;

// Change to unit subdirectory
process.chdir(__dirname + '/unit');

reporter.run([
    'test_db_print.js'
  , 'test_db_query.js'
]);
